ci(workflows): [`release`] `on.pull_request` -> `on.push`
Signed-off-by: Lexus Drumgold <unicornware@flexdevelopment.llc>

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,6 +1,6 @@
 # Release
 #
-# Publish a GitHub release on release branch merge.
+# Publish a GitHub release after a release is merged.
 #
 # References:
 #
@@ -8,34 +8,31 @@
 # - https://docs.github.com/actions/learn-github-actions/contexts
 # - https://docs.github.com/actions/learn-github-actions/expressions
 # - https://docs.github.com/actions/reference/workflows-and-actions/workflow-commands
-# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
+# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#push
 # - https://docs.github.com/actions/using-workflows/using-github-cli-in-workflows
 # - https://docs.github.com/actions/using-workflows/workflow-commands-for-github-actions
-# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request
+# - https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads#push
 # - https://git-scm.com/book/en/v2/Git-Basics-Tagging
 # - https://github.com/actions/checkout
 # - https://github.com/crazy-max/ghaction-import-gpg
 # - https://github.com/flex-development/dist-tag-action
 # - https://github.com/flex-development/gh-release-url-action
 # - https://github.com/flex-development/grease
-# - https://github.com/flex-development/jq-action
 # - https://github.com/flex-development/manver-action
 # - https://github.com/hmarr/debug-action
+# - https://github.com/kaisugi/action-regex-match
+# - https://regex101.com/r/wu576x
 # - https://yarnpkg.com/cli/pack
 
 ---
 name: release
 on:
-  pull_request:
+  push:
     branches:
       - main
-    types:
-      - closed
-env:
-  ref_name: ${{ format('{0}@{1}', github.base_ref, github.event.pull_request.merge_commit_sha) }}
 jobs:
   preflight:
-    if: ${{ startsWith(github.head_ref, 'release/') && github.event.pull_request.merged }}
+    if: ${{ startsWith(github.event.head_commit.message, 'release:') }}
     permissions:
       contents: read
     runs-on: ubuntu-latest
@@ -47,11 +44,35 @@ jobs:
       - id: debug
         name: Print environment variables and event payload
         uses: hmarr/debug-action@v3.0.0
+      - id: fail-actor
+        if: contains(vars.MAINTAINERS, github.actor) == false
+        name: Fail on unauthorized actor
+        run: |
+          echo '**Unauthorized actor: ${{ github.actor }}**' >>$GITHUB_STEP_SUMMARY
+          exit 1
+      - id: metadata
+        name: Check head commit message
+        uses: kaisugi/action-regex-match@v1.0.2
+        with:
+          flags: u
+          regex: ${{ vars.RELEASE_MERGED_REGEX }}
+          text: ${{ github.event.head_commit.message }}
+      - id: fail-metadata
+        if: steps.metadata.outputs.match == ''
+        name: Fail on invalid release merge message
+        run: |
+          err='**Invalid release merge message**
+          ```sh
+          ${{ github.event.head_commit.message }}
+          ```
+          Message must match [`${{ vars.RELEASE_MERGED_REGEX }}`](https://regex101.com/r/wu576x)'
+          echo "$err" >>$GITHUB_STEP_SUMMARY
+          exit 1
       - id: checkout
-        name: Checkout ${{ env.ref_name }}
+        name: Checkout ${{ github.ref_name }}
         uses: actions/checkout@v7.0.1
         with:
-          ref: ${{ github.event.pull_request.merge_commit_sha }}
+          ref: ${{ github.sha }}
       - id: version
         name: Get release version
         uses: flex-development/manver-action@1.1.0
@@ -77,12 +98,12 @@ jobs:
       NOTES_FILE: RELEASE_NOTES.md
     steps:
       - id: checkout
-        name: Checkout ${{ env.ref_name }}
+        name: Checkout ${{ github.ref_name }}
         uses: actions/checkout@v7.0.1
         with:
           fetch-depth: 0
           persist-credentials: true
-          ref: ${{ github.event.pull_request.merge_commit_sha }}
+          ref: ${{ github.sha }}
           token: ${{ env.GITHUB_TOKEN }}
       - id: gpg-import
         name: Import GPG key
@@ -110,14 +131,14 @@ jobs:
         run: echo "${{ github.workspace }}/node_modules/.bin" >> ${{ github.path }}
       - id: build
         name: Add build metadata to package.json
-        run: yq '.build="${{ github.event.pull_request.merge_commit_sha }}"' -i package.json
+        run: yq '.build="${{ github.sha }}"' -i package.json
       - id: pack
         name: Pack project
         run: |
           mv CHANGELOG.md _CHANGELOG.md
           yarn pack --out %s-%v.tgz
           mv _CHANGELOG.md CHANGELOG.md
-      - id: release-notes
+      - id: notes
         name: Generate release notes
         env:
           TZ: ${{ vars.TZ }}
